---
title: "OPC Farallons End Products"
format: gfm
editor: visual
---

```{r}
#| output: false
#| echo: false

library(tidyverse)
library(purrr)
library(stringr)

# Final output should look like:
# <details>
#   <summary>2023</summary>
#   <details>
#     <summary>03</summary>
#     [anchovy_2023-03-01.grd](anchovy_2023-03-01.grd)
#     [anchovy_2023-03-01.gri](anchovy_2023-03-01.gri)
#     ...
#     [anchovy_2023-03-31.grd](anchovy_2023-03-31.grd)
#     [anchovy_2023-03-31.gri](anchovy_2023-03-31.gri)
#     ...
#     [bluewhale_2023-03-01.grd](bluewhale_2023-03-01.grd)
#     [bluewhale_2023-03-01.gri](bluewhale_2023-03-01.gri)
#     ...
#     [humpback_2023-03-31.grd](humpback_2023-03-31.grd)
#     [humpback_2023-03-31.gri](humpback_2023-03-31.gri)
#   </details>
#   ...
#   <details>
#     <summary>12</summary>
#     [anchovy_2023-12-01.grd](anchovy_2023-12-01.grd)
#     ...
#     [humpback_2023-12-31.gri](humpback_2023-12-31.gri)
#   </details>
# </details>
# ...

# Generate Markdown output for a given year
print_year <- function(year, rows) {
  months <- rows %>% 
    nest(.by = month) %>% 
    mutate(markdown = map2_chr(month, data, print_month)) %>% 
    pull(markdown) %>% 
    paste0(collapse = "\n")
  str_glue("
  <details>
    <summary>{year}</summary>
    {months}
  </details>
  ")
}

# Generate Markdown output for a given month
print_month <- function(month, rows) {
  links <- str_glue("[{rows$file_path}]({rows$file_path})") %>% 
    paste0(collapse = "\n\n")
  str_glue("
  <details>
    <summary>{month}</summary>
    {links}
  </details>
  ")
}

```

## Daily rasters

```{r}
#| output: asis
#| echo: false



raster_paths <- dir("rasters", pattern = ".*.gr[di]") 
raster_paths %>% 
  str_split("[_-]") %>% 
  map(\(x) tibble(species = x[1],
                  year = x[2],
                  month = x[3],
                  day = str_sub(x[4], 1, 2),
                  extension = str_sub(x[4], 3))) %>% 
  list_rbind() %>% 
  mutate(file_path = raster_paths) %>% 
  nest(.by = year) %>% 
  mutate(markdown = map2_chr(year, data, print_year)) %>% 
  pull(markdown) %>% 
  paste0(collapse = "\n") %>% 
  cat()

```

## Daily maps

```{r}
#| output: asis
#| echo: false



raster_paths <- dir("maps", pattern = ".png") 
raster_paths %>% 
  str_split("[_-]") %>% 
  map(\(x) tibble(species = x[1],
                  year = x[2],
                  month = x[3],
                  day = str_sub(x[4], 1, 2),
                  extension = str_sub(x[4], 3))) %>% 
  list_rbind() %>% 
  mutate(file_path = raster_paths) %>% 
  nest(.by = year) %>% 
  mutate(markdown = map2_chr(year, data, print_year)) %>% 
  pull(markdown) %>% 
  paste0(collapse = "\n") %>% 
  cat()

```

## Daily EPAC metadata

```{r}
#| output: asis
#| echo: false



raster_paths <- dir("epac_metadata", pattern = ".csv") 
raster_paths %>% 
  str_split("[_-]") %>% 
  map(\(x) tibble(
                  year = x[2],
                  month = x[3],
                  day = str_sub(x[4], 1, 2),
                  extension = str_sub(x[4], 3))) %>% 
  list_rbind() %>% 
  mutate(file_path = raster_paths) %>% 
  nest(.by = year) %>% 
  mutate(markdown = map2_chr(year, data, print_year)) %>% 
  pull(markdown) %>% 
  paste0(collapse = "\n") %>% 
  cat()

```

## Two week rasters

```{r}
#| output: asis
#| echo: false



raster_paths <- dir("two_week_rasters", pattern = ".*.gr[di]") 
raster_paths %>% 
  gsub("end","",.) %>% 
  str_split("[_-]") %>% 
  map(\(x) tibble(species = x[1],
                  year = x[2],
                  month = x[3],
                  day = x[4],
                  extension = str_sub(x[7], 2))) %>% 
  list_rbind() %>% 
  mutate(file_path = raster_paths) %>% 
  nest(.by = year) %>% 
  mutate(markdown = map2_chr(year, data, print_year)) %>% 
  pull(markdown) %>% 
  paste0(collapse = "\n") %>% 
  cat()

```

## Two week maps

```{r}
#| output: asis
#| echo: false



raster_paths <- dir("two_week_maps", pattern = ".png") 
raster_paths %>% 
  gsub("start","",.) %>% 
  str_split("[_-]") %>% 
  map(\(x) tibble(species = x[1],
                  year = x[2],
                  month = x[3],
                  day = x[4],
                  extension = str_sub(x[7], 2))) %>% 
  list_rbind() %>% 
  mutate(file_path = raster_paths) %>% 
  nest(.by = year) %>% 
  mutate(markdown = map2_chr(year, data, print_year)) %>% 
  pull(markdown) %>% 
  paste0(collapse = "\n") %>% 
  cat()

```

## Two week metadata

```{r}
#| output: asis
#| echo: false



raster_paths <- dir("two_week_metadata", pattern = ".csv") 
raster_paths %>% 
  str_split("[_-]") %>% 
  map(\(x) tibble(species = x[1],
                  year = x[3],
                  month = x[4],
                  day = str_sub(x[5], 1, 2),
                  extension = str_sub(x[5], 2))) %>% 
  list_rbind() %>% 
  mutate(file_path = raster_paths) %>% 
  nest(.by = year) %>% 
  mutate(markdown = map2_chr(year, data, print_year)) %>% 
  pull(markdown) %>% 
  paste0(collapse = "\n") %>% 
  cat()

```
